### PR TITLE
Update to curv@0.9.

### PR DESCRIPTION
**Pull request by tmpfs**
We also have to update this library for `multi-party-ecdsa` otherwise there is a cargo error with mismatched dependencies.

### CODE REVIEW

**Comment by tmpfs** [comment]
@survived, what should is the replacement for `bytes_compressed_to_big_int()` please?

**Comment by tmpfs** [comment]
@survived, down to one compiler error but I am a little bit stumped by this:

```
error[E0277]: the trait bound `BigInt: RingNormalize` is not satisfied
   --> src/lib.rs:350:29
    |
350 |         let mut b: BigInt = ring_algorithm::chinese_remainder_theorem(&[b1, b0], &[a1, g])?;
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `RingNormalize` is not implemented for `BigInt`
    |
   ::: /home/muji/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-algorithm-0.2.3/src/lib.rs:228:74
    |
228 |     T: sealed::Sized + Clone + Eq + num_traits::Zero + num_traits::One + RingNormalize,
    |                                                                          ------------- required by this bound in `chinese_remainder_theorem`
```

Clearly `BigInt` would need to implement `RingNormalize` but I am not clear whether implementing this trait is a new requirement and how this ever worked.

Also I noticed that `ring_algorithm@0.2.3` which is in the cargo dependency list has been yanked: https://docs.rs/ring-algorithm/0.2.3/ring_algorithm/trait.RingNormalize.html

**Comment by survived** [comment]
> what is the replacement for bytes_compressed_to_big_int() please?

> So I ended up using BigInt::from_bytes() on the reference of the EncodedPoint

You're completely right, it should nicely match previous behaviour

> please check I got the update to the Hmac handling correct

Yep, you got it correctly. I would even get rid of `HmacSha512` type alias, `Hmac<Sha512>` should work just fine.

> Also I noticed that ring_algorithm@0.2.3 which is in the cargo dependency list has been yanked

We used to have `curv`'s bigints implementing `RingNormalize` trait, but the crate was yanked as you correctly observed. That's basically why we removed dependency on `ring_algorithm` in `curv` (by copypasting algorithms that we used to use). I would suggest to do the same in this crate, let me try to do this - I'll copypast `chinese_remainder_theorem` and we won't need to introduce this dependency again.

**Comment by tmpfs** [comment]
Thanks @survived, I now have `multi-party-ecdsa` spitting out all the usual compiler errors so it looks like we are on the home stretch for the upgrade :+1:

**Comment by survived** [comment]
Great, @tmpfs! While you're fighting with `multi-party-ecdsa`, I'll resolve these clippy warnings we have here

**Pull request merged**
